### PR TITLE
Add Findoctomap module

### PR DESCRIPTION
**Pull request by rojkov**
octomap's authors use absolute paths in the cmake module they
ship together with the package. This makes the module unusable
in cross-compilation environments or requires additional
tweaking (e.g. see https://github.com/bmwcarit/meta-ros/blob/43bd17e8839f4078351895eca361804f19efb13c/recipes-ros/octomap-ros/octomap-ros_0.4.0.bb#L16)

This patch overrides the module in order to ease octomap's
usage in cross-compilation environments.

Signed-off-by: Dmitry Rozhkov <dmitry.rozhkov@linux.intel.com>

### CODE REVIEW

**Comment by wjwwood** [comment]
@ahornung do you have any input on this? Maybe this would be better to exist in `octomap_ros`?

**Comment by rojkov** [comment]
Beside `octomap_ros` I had similar problems with `MoveIt!`, `geometric_shapes` and `collada_urdf`.

**Comment by ahornung** [comment]
I'm not sure I fully understand the need for this... after all it creates a second `find_package` command for OctoMap and in consequence two places to maintain for similar functionality. The variables are named similarly as in the OctoMap CMake config but with different capitalization, which could make hard to understand for a user which one is actually used in the end.

Wouldn't it be better to ease cross-compilation directly in OctoMap? It'll have to be done in a compatible way that does not affect regular compilation, e.g. with a CMake config option.

**Comment by ahornung** [comment]
Was the absolute path issue (also mentioned in https://github.com/OctoMap/octomap/pull/104) not already fixed with https://github.com/OctoMap/octomap/pull/118?

**Comment by rojkov** [comment]
Right. I didn't notice there's the `devel` branch and tested with the latest `master` only.

With https://github.com/OctoMap/octomap/pull/118 backported to Octomap 1.8.0 cross-compilation works well. Thanks!

Closing...

**Pull request closed without merging**
