### PR TITLE
Add FindTinyXML2 module

### PR DESCRIPTION
**Pull request by rojkov**
rospack might use this module in future

### CODE REVIEW

**Comment by dirk-thomas** [comment]
@wjwwood Is there a reason why this hasn't been merged and released yet? It will be needed for rospack.

**Comment by wjwwood** [comment]
No reason, just haven't reviewed it yet. It's on my list of things to review for lunar. Just glancing at it, it looks ok to me. Feel free to merge if it is useful to you.

**Comment by dirk-thomas** [comment]
Until it is released the rospack PR test won't work. I will wait for the Lunar release then.

I was just wondering if you intentionally leave this to be merged into a new lunar branch or if it will be merged and released from the current default branch (targeting Jade and higher).

**Comment by wjwwood** [comment]
I don't have strong preference. If it is needed in Jade and newer I can do that. Otherwise, I'd put it in just Lunar simply to reduce new stuff in existing distros and avoid extra rebuilds on the farm.

**Comment by wjwwood** [comment]
The reason is not to wait for lunar, but that's just the next time I was gonna spend time on this repository unless something urgent came up.

**Comment by dirk-thomas** [comment]
The rospack PR will only target Lunar. So I don't mind into which branch this gets released.

**Review by wjwwood — APPROVED** [review]
lgtm

**Pull request merged**
