### PR TITLE
Adding r36 of FindTBB.cmake from the findtbb package

### PR DESCRIPTION
**Pull request by piyushk**
I've copied over FindTBB.cmake from the findtbb project: https://code.google.com/p/findtbb/

### CODE REVIEW

**Comment by piyushk** [comment]
The module file seems to be working fine, and I can build stuff.

There is a small discrepancy in the make output that I am unsure about. Take a look at the (very new) clasp 2.1.4 package: https://github.com/utexas-bwi/bwi_planning

When I run `catkin_make`, I do see the following line as expected:

```
-- Found TBB_LIBRARIES: /usr/lib/libtbb.so;/usr/lib/libtbbmalloc.so
```

However, when I run `catkin_make --make-args VERBOSE=1`, I see the following output:

```
/usr/bin/c++       CMakeFiles/clasp_app.dir/app/clasp_options.cpp.o CMakeFiles/clasp_app.dir/app/clasp_app.cpp.o CMakeFiles/clasp_app.dir/app/clasp_output.cpp.o CMakeFiles/clasp_app.dir/app/alarm.cpp.o CMakeFiles/clasp_app.dir/app/main.cpp.o  -o /home/piyushk/catkin_ws/devel/lib/clasp/clasp -rdynamic /home/piyushk/catkin_ws/devel/lib/libclasp.so /home/piyushk/catkin_ws/devel/lib/libprogram_opts.so -ltbb -ltbbmalloc -Wl,-rpath,/home/piyushk/catkin_ws/devel/lib 
```

Note that this says `-ltbb -ltbbmalloc` instead of `/usr/lib/libtbb.so /usr/lib/libtbbmalloc.so`. I'm not exactly sure if this is some cmake magic, or something that might cause cross-platform compatibility issues.

**Comment by tfoote** [comment]
I expect that is fine.  It probably detected that the files are on your library path already. If you can verify that it's actually using the module I expect it's ok.  And not diverging from upstream is always better. If we do find an issue we should submit it upstream and merge it when it's taken upstream.

**Comment by tfoote** [comment]
Sorry not supposed to close that.

**Comment by wjwwood** [comment]
+1, it appears to follow the conventions laid out here:

https://github.com/ros/cmake_modules/blob/master/CONTRIBUTING.md

**Comment by piyushk** [comment]
I've confirmed that the module is being used, and code builds correctly.

**Comment by piyushk** [comment]
@wjwwood Would it be possible to churn out a new release? I am trying to release a dependent package over the next 2 weeks.

**Comment by wjwwood** [comment]
Done:
- hydro: https://github.com/ros/rosdistro/pull/2681
- groovy: https://github.com/ros/rosdistro/pull/2682

**Comment by piyushk** [comment]
Thanks!

**Pull request merged**
