### PR TITLE
Added CMake module for finding the UUID libraries

### PR DESCRIPTION
**Pull request by esteve**
This branch adds a CMake module for finding UUID libraries in a cross-platform way. Starting with Mac OSX Yosemite, `nodelet` and `bondcpp` can no longer find the UUID libraries using plain `target_link_libraries`

### CODE REVIEW

**Comment by esteve** [comment]
See https://github.com/ros/bond_core/issues/6 and https://github.com/ros/nodelet_core/issues/26 for more info.

**Comment by wjwwood** [comment]
Can you look over this guide: https://github.com/ros/cmake_modules/blob/0.3-devel/CONTRIBUTING.md and add docs for the Module?

**Comment by esteve** [comment]
@wjwwood I think the documentation I added is correct, but let me know if there's anything I should fix or add. Thanks.

**Comment by wjwwood** [comment]
Lgtm, +1

**Pull request merged**
