### PR TITLE
Add CMake searcher for DepthSenseSDK.

### PR DESCRIPTION
**Pull request by kamiccolo**
Adds CMake module for searching for DepthSenseSDK includes and libraries.

**What the heck is that?**
DepthSenseSDK --- product of SoftKinetic, developed as an interface for their stereo-cameras.  Those are use by at least couple of ROS users I know. 

Oh, besides, it's also released for [Windows](http://www.softkinetic.com/Support/Download), so, adding relevant searcher rules.

### CODE REVIEW

**Comment by wjwwood** [comment]
Thanks for the pull request, but I won't be releasing any changes to the `0.2-devel` branch since that is Groovy only and Groovy has been EOL'ed. I'd happily take the new module for `0.4-devel` and ROS Jade. I would consider a pull request for `0.3-devel` which is for ROS Hydro and Indigo, though I'm more careful about merging to that branch and I make releases from that branch less frequently.

**Comment by kamiccolo** [comment]
Thanks for response. I was aware of 0.2-devel being the one for Groovy which was EOLed, just thought of developers building packages from source them selves. And this might be a handy addition despite not getting pulled into the *.deb repository.

 Will apply the mentioned pull-request to 0.3-devel and 0.4-devel respectively. Besides, also forgot README additions :}

**Comment by wjwwood** [comment]
I'll merge this, but I won't be releasing it.

**Comment by kamiccolo** [comment]
Still thanks :)

**Pull request merged**
