### PR TITLE
0.5 Noetic release only

### PR DESCRIPTION
**Pull request by sloretz**

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Why does this need a Noetic-only branch and can't continue to use the same one as Kinetic / Melodic?

**Review by wjwwood — APPROVED** [review]
Thanks.

**Comment by wjwwood** [comment]
Jade cannot support this change.

**Comment by wjwwood** [comment]
I was hesitant to change the required cmake version in Kinetic, Melodic, etc. I can reconsider that.

**Comment by dirk-thomas** [comment]
I was just curious. If you want to maintain separate branches that is fine with me. Other repos have applied the same change for Kinetic, Melodic and Noetic.

**Pull request merged**
